"""Application-facing orchestration for retrieval, prompting, and generation."""

from __future__ import annotations

import logging
from typing import Any, Iterable, Literal, Mapping

from pydantic import BaseModel, Field

from services.PromptBuilder import GenerationMode, PromptBuilder

logger = logging.getLogger(__name__)


class GenerationSource(BaseModel):
    """Application-owned source metadata; it is never generated by the LLM."""

    email_id: str = ""
    chunk_id: str = ""
    subject: str = ""


class GenerationResult(BaseModel):
    answer: str
    sources: list[GenerationSource] = Field(default_factory=list)


class GenerationService:
    """Answer a query or draft an email using retrieved inbox context."""

    def __init__(self, retriever: Any, prompt_builder: PromptBuilder, llm_client: Any) -> None:
        self.retriever = retriever
        self.prompt_builder = prompt_builder
        self.llm_client = llm_client

    def generate(
        self,
        query: str,
        mode: GenerationMode = "question_answering",
        top_k: int = 5,
        history: Iterable[Mapping[str, str]] | None = None,
    ) -> GenerationResult:
        results = self.retriever.retrieve(query=query, top_k=top_k)
        logger.info(
            "Retrieved %d chunks for query (mode=%s, top_k=%d)",
            len(results),
            mode,
            top_k,
        )
        messages = self.prompt_builder.build_messages(
            query=query, results=results, mode=mode, history=history
        )
        logger.info(
            "Building generation prompt from %d retrieved chunks; LLM receives %d messages",
            len(results),
            len(messages),
        )
        answer = self.llm_client.generate(messages)
        logger.info(
            "LLM generation finished (answer length=%d, sources=%d)",
            len(answer),
            len(results),
        )
        return GenerationResult(answer=answer, sources=self._sources_from(results))

    @staticmethod
    def _sources_from(results: Iterable[Mapping[str, Any]]) -> list[GenerationSource]:
        sources = []
        seen_ids = set()
        for result in results:
            metadata = result.get("metadata") or {}
            if not isinstance(metadata, Mapping):
                metadata = {}
            chunk_id = str(result.get("id") or result.get("chunk_id") or "")
            if chunk_id in seen_ids:
                continue
            seen_ids.add(chunk_id)
            sources.append(
                GenerationSource(
                    email_id=str(metadata.get("email_id") or result.get("email_id") or ""),
                    chunk_id=chunk_id,
                    subject=str(metadata.get("subject") or result.get("subject") or ""),
                )
            )
        return sources
